mi03_vitrine:
    resource: "@mi03VitrineBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

    requirements:
        _locale: en|fr

app:
    resource: '@AppBundle/Controller/'
    type: annotation
