# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        mi03\VitrineBundle\Entity\Client:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        utilisateurs:
            entity: { class: mi03VitrineBundle:Client, property: mail}

    firewalls:
        vitrine_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /fr/login
                check_path:  /fr/login
            logout:
                path: /fr/logout
                target: /fr/accueil
    access_control:
        - { path: ^/(en|fr)/client$, roles: ROLE_USER}
        - { path: ^/(en|fr)/commande$, roles: ROLE_USER}
        - { path: ^/(en|fr)/backoffice$, roles: ROLE_ADMIN}
        - { path: ^/(en|fr)/edit$, roles: ROLE_ADMIN}
        - { path: ^/(en|fr)/commande$, roles: ROLE_ADMIN}
        - { path: ^/(en|fr)/article$, roles: ROLE_ADMIN}
