mi03\VitrineBundle\Entity\Client:
  type: entity
  table: client
  id:
    id:
      type: integer
      generator: { strategy: AUTO}
  fields:
    nom:
      type: string
      length: 100
    mail:
      type: string
      length: 100
    password:
      type: string
      length: 20
  oneToMany:
    commandes:
      targetEntity: Commande
      mappedBy: client