mi03_vitrine_client:
    resource: "@mi03VitrineBundle/Resources/config/routing/client.yml"
    prefix:   /client

mi03_vitrine_category:
        resource: "@mi03VitrineBundle/Resources/config/routing/category.yml"
        prefix:   /category

mi03_vitrine_article:
        resource: "@mi03VitrineBundle/Resources/config/routing/article.yml"
        prefix:   /article

mi03_vitrine_homepage:
    path:     /accueil/{name}
    defaults: {
        _controller: mi03VitrineBundle:Default:index,
        name : visiteur}

mi03_vitrine_mentions:
    path:   /mentions
    defaults: {_controller: mi03VitrineBundle:Default:mentions}

mi03_vitrine_catalogue:
    path:   /catalogue
    defaults: {_controller: mi03VitrineBundle:Catalogue:index}

mi03_vitrine_articleParCategorie:
    path: /articleParCategorie/{id}
    defaults: {_controller: mi03VitrineBundle:Catalogue:articleParCategorie}

mi03_vitrine_panier:
    path: /panier
    defaults: {_controller: mi03VitrineBundle:Panier:index}

mi03_vitrine_panier_supprimer_ligne_commande:
    path: /deleteLigneCommandePanier/{idArticle}
    defaults: {_controller: mi03VitrineBundle:Panier:deleteArticlePanier}

mi03_vitrine_panier_change_quantity_article:
    path: /changeQuantityArticlePanier/{idArticle}
    defaults: {_controller: mi03VitrineBundle:Panier:changeQuantityArticlePanier}

mi03_vitrine_ajouter_article:
    path: /ajouterArticle/{id}
    defaults: {_controller: mi03VitrineBundle:Catalogue:ajouterArticle}

mi03_vitrine_vider_panier:
    path: /viderPanier
    defaults: {_controller: mi03VitrineBundle:Panier:viderPanier}

mi03_vitrine_validation_panier:
    path: /validationPanier
    defaults: {_controller: mi03VitrineBundle:Panier:validerPanier}

mi03_vitrine_commande:
    resource: "@mi03VitrineBundle/Resources/config/routing/commande.yml"
    prefix:   /commande

mi03_clear_session:
    path: /clear_session
    defaults: {_controller: mi03VitrineBundle:Default:clearSession}

mi03_vitrine_login:
    path: /login
    defaults: {_controller: mi03VitrineBundle:Security:login}

mi03_vitrine_logout:
    path: /logout
    defaults: {_controller: mi03VitrineBundle:Security:logout}

mi03_vitrine_signin:
    path: /register
    defaults: {_controller: mi03VitrineBundle:Security:create}

mi03_vitrine_backoffice_homepage:
    path: /backoffice
    defaults: {_controller: mi03VitrineBundle:Default:indexBackOffice}
