services:
#    mi03_vitrine.example:
#        class: mi03\VitrineBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  mi03_vitrine.panierToCommande:
    class : mi03\VitrineBundle\Services\PanierUtils
    arguments: ["@doctrine.orm.entity_manager"]

  miO3_vitrine.mailerUtils:
    class : mi03\VitrineBundle\Services\MailerUtils
    arguments: ["@swiftmailer.mailer","@templating.engine.twig"]