services:
#    mi03_vitrine.example:
#        class: mi03\VitrineBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  mi03_vitrine.panierToCommande:
    class : mi03\VitrineBundle\Services\ConvertPanierToCommande
    arguments: ["@doctrine.orm.entity_manager"]

  mi03_vitrine_montantPanier:
    class : mi03\VitrineBundle\Services\PricePanier
    arguments: ["@doctrine.orm.entity_manager"]